# This is a basic workflow to showcase the use of Reusable Workflows

name: Reusable Workflow user

on:
  workflow_dispatch:

jobs:
  do-it:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Run a one-line script
        run: echo Hello, world!

  docker:
    uses: chitransh93/ReusableWorkflow/.github/workflows/buildAndPublishDockerImage.yml@main
    with:
      image_name: chitransh93/maven-container
      tag: latest2
    secrets:
      registry_username: ${{secrets.DOCKER_USERNAME}}
      registry_password: ${{secrets.DOCKER_PASSWORD}}
